name: Publish Smarty-ui-vite To Npm

on:
  push:
    branches: [publish]

jobs:
  publish:
    runs-on: ubuntu-latest

    # name: "publish npm"

    # environment: npm

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 7.2.1
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org/'
          always-auth: true
      - name: Debug .npmrc
        run: cat .npmrc

      - name: Debug pnpm version
        run: pnpm --version
      - name: Check environment variable
        run: |
          if [ -z "${{ secrets.UI_TEST_NPM_TOKEN }}" ]; then
            echo "UI_TEST_NPM_TOKEN is not set."
          else
            echo "UI_TEST_NPM_TOKEN is set."
          fi
      - name: Install modules
        run: pnpm install
        env:
          NPM_CONFIG_AUTO_INSTALL_PEERS: "true"
          NPM_CONFIG_STRICT_PEER_DEPENDENCIES: "false"
          NPM_CONFIG_REGISTRY: "https://registry.npmjs.org/"
          NPM_TOKEN: ${{ secrets.UI_TEST_NPM_TOKEN }}
      - name: Ensure clean working directory
        run: |
          git diff --exit-code || (git add . && git commit -m "Auto commit before publish" && git push origin publish ) || true
      - name: Build and test
        run: pnpm run build
      # --no-git-checks 是不检查git工作目录状态，可能会造成还有代码没有提交但是发包了，需要慎用，但是目前不加这个一直报错说工作目录不干净，所以待解决
      - name: Publish package
        run: npm set regostry https://registry.npmjs.org/ && npm publish --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{secrets.UI_TEST_NPM_TOKEN}}


      # - uses: actions/checkout@master
      # - uses: pnpm/action-setup@v2.1.0
      #   with:
      #     version: 6.31.0
      # - name: Install modules
      #   run: pnpm install
      # - name: Build
      #   run: cd /home/runner/work/ui-test/ui-test && npm run build
      # - name: Publish package
      #   run: npm publish --access public
      #   env:
      #     NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}


      # - name: "Publish to the npm registry"
      #   # uses: primer/publish@3.0.0
      # # - run: npm publish
      # - uses: JS-DevTools/npm-publish@v3
      #   with: 
      #     token: ${{ secrets.ui-test-token }} 
          # 跟前面步骤中的 NPM_AUTH_TOKEN 保持一致
        # env:
        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        #   NPM_AUTH_TOKEN: ${{ secrets.ui-test-token }} # 跟前面步骤中的 NPM_AUTH_TOKEN 保持一致
        # with:
        #   default_branch: "publish"
        #   dir: "/home/runner/work/ui-test/ui-test"
